// AITutorialPages.js - page list for the AI / LLM Learn track dropdown
const tutorialPages = [
  { name: "Intro - Tutorial index", url: "Learn_intro.html" },
  { name: "Hello - First LLM API Call", url: "AI_Tutorial__Hello.html" },
  { name: "Tools - SDK, API Key, Environment", url: "AI_Tutorial__Tools.html" },
  { name: "Messages - Conversation Structure", url: "AI_Tutorial__Messages.html" },
  { name: "Tokens - Context Windows and Cost", url: "AI_Tutorial__Tokens.html" },
  { name: "Prompting - Effective Prompts for Code", url: "AI_Tutorial__Prompting.html" },
  { name: "System Prompts - Controlling Behavior", url: "AI_Tutorial__System_Prompts.html" },
  { name: "Streaming - Real-Time Responses", url: "AI_Tutorial__Streaming.html" },
  { name: "Models - Choosing the Right Model", url: "AI_Tutorial__Models.html" },
  { name: "Errors - Handling API Failures", url: "AI_Tutorial__Errors.html" },
  { name: "Testing - Evaluating AI Output", url: "AI_Tutorial__Testing.html" },
  { name: "App: Chat Loop - Console Chat", url: "AI_Tutorial__App_Chat_Loop.html" },
  { name: "App: Code Explainer - File Analysis", url: "AI_Tutorial__App_Code_Explainer.html" },
  { name: "App: Code Review - Automated Review", url: "AI_Tutorial__App_Code_Review.html" },
  { name: "App: Test Generator - Generate Tests", url: "AI_Tutorial__App_Test_Generator.html" },
  { name: "App: Diff Reviewer - Compare Versions", url: "AI_Tutorial__App_Diff_Reviewer.html" },
  { name: "App: Web Chat - Flask Chat Interface", url: "AI_Tutorial__App_Web_Chat.html" },
  { name: "App: Web Code Review - Form Submission", url: "AI_Tutorial__App_Web_Code_Review.html" },
  { name: "App: Web Streaming - SSE Responses", url: "AI_Tutorial__App_Web_Streaming.html" },
  { name: "App: Tool Use - Function Calling", url: "AI_Tutorial__App_Tool_Use.html" },
  { name: "App: Simple Agent - File-Reading Agent", url: "AI_Tutorial__App_Simple_Agent.html" },
  { name: "Demonstrations - Code Helper Tool", url: "AI_Tutorial__Demonstrations.html" },
];
