// CSharpTutorialPages.js - page list for the C# Learn track dropdown
const tutorialPages = [
  { name: "Intro - Tutorial index", url: "Learn_intro.html" },
  { name: "Hello - Your First C# Program", url: "CSharpTutorial__Hello.html" },
  { name: "Tools - .NET Development Toolchain", url: "CSharpTutorial__Tools.html" },
  { name: "Variables - C# Types and Variables", url: "CSharpTutorial__Variables.html" },
  { name: "Functions - C# Methods", url: "CSharpTutorial__Functions.html" },
  { name: "Control Flow - C# Execution Control", url: "CSharpTutorial__Control_Flow.html" },
  { name: "Classes - C# Classes and Objects", url: "CSharpTutorial__Classes.html" },
  { name: "Interfaces - Contracts and Polymorphism", url: "CSharpTutorial__Interfaces.html" },
  { name: "Enums - C# Enumeration Types", url: "CSharpTutorial__Enums.html" },
  { name: "Generics - Generic Programming", url: "CSharpTutorial__Generics.html" },
  { name: "Testing - xUnit Unit Testing", url: "CSharpTutorial__Testing.html" },
  { name: "Strings - System.String Operations", url: "CSharpTutorial__StdLib_Strings.html" },
  { name: "List - List<T>", url: "CSharpTutorial__StdLib_List.html" },
  { name: "Dictionary - Dictionary<K,V>", url: "CSharpTutorial__StdLib_Dictionary.html" },
  { name: "Exceptions - try/catch/finally", url: "CSharpTutorial__StdLib_Exceptions.html" },
  { name: "File I/O - System.IO", url: "CSharpTutorial__StdLib_FileIO.html" },
  { name: "LINQ - Query Language", url: "CSharpTutorial__StdLib_LINQ.html" },
  { name: "Delegates - Action, Func, Lambda", url: "CSharpTutorial__StdLib_Delegates.html" },
  { name: "Async - async/await and Task", url: "CSharpTutorial__StdLib_Async.html" },
  { name: "Formatting - String Interpolation", url: "CSharpTutorial__StdLib_Formatting.html" },
  { name: "Records - Record Types", url: "CSharpTutorial__Records.html" },
  { name: "Demonstrations - dotnet demo projects", url: "CSharpTutorial__Demonstrations.html" },
];
