// PythonTutorialPages.js - page list for the Python Learn track dropdown
const tutorialPages = [
  { name: "Intro - Tutorial index", url: "Learn_intro.html" },
  { name: "Hello - Your First Python Program", url: "PythonTutorial__Hello.html" },
  { name: "Tools - Python Development Toolchain", url: "PythonTutorial__Tools.html" },
  { name: "Variables - Python Types and Variables", url: "PythonTutorial__Variables.html" },
  { name: "Functions - Python Functions", url: "PythonTutorial__Functions.html" },
  { name: "Control Flow - Python Execution Control", url: "PythonTutorial__Control_Flow.html" },
  { name: "Classes - Python Classes", url: "PythonTutorial__Classes.html" },
  { name: "Modules - Python Import System", url: "PythonTutorial__Modules.html" },
  { name: "Enums - Python enum Module", url: "PythonTutorial__Enums.html" },
  { name: "Testing - pytest", url: "PythonTutorial__Testing.html" },
  { name: "Comprehensions - List and Dict Expressions", url: "PythonTutorial__Comprehensions.html" },
  { name: "Strings - str Operations", url: "PythonTutorial__StdLib_Strings.html" },
  { name: "Lists - list Operations", url: "PythonTutorial__StdLib_Lists.html" },
  { name: "Dicts - dict Operations", url: "PythonTutorial__StdLib_Dicts.html" },
  { name: "Exceptions - try/except/finally", url: "PythonTutorial__StdLib_Exceptions.html" },
  { name: "File I/O - open() and pathlib", url: "PythonTutorial__StdLib_FileIO.html" },
  { name: "Iterators - Iterator Protocol", url: "PythonTutorial__StdLib_Iterators.html" },
  { name: "Closures - Functions and Decorators", url: "PythonTutorial__StdLib_Closures.html" },
  { name: "Threads - threading and asyncio", url: "PythonTutorial__StdLib_Threads.html" },
  { name: "Formatting - f-strings and format()", url: "PythonTutorial__StdLib_Formatting.html" },
  { name: "Dataclasses - @dataclass", url: "PythonTutorial__Dataclasses.html" },
  { name: "Demonstrations - Python demo scripts", url: "PythonTutorial__Demonstrations.html" },
];
