[package]
name = "input"
version = "0.1.0"
edition = "2018"

[dependencies]
compute = { path = "../Compute" }
file_utils = { path = "../Fileutils" }

[dev-dependencies]
tempfile = "3"      # tempfile crate from crates.io
