> cargo run -q

  -- DataFlowStructure::Executive --

  file "./src/main.rs" has 52 lines of code      

  file "../Input/src/lib.rs" has 78 lines of code
  file "../Input/examples/test1.rs" has 18 lines of code

  file "../Compute/src/lib.rs" has 105 lines of code
  file "../Compute/examples/test1.rs" has 27 lines of code

  file "../Output/src/lib.rs" has 24 lines of code
  file "../Output/examples/test1.rs" has 16 lines of code

  file "../Fileutils/src/lib.rs" has 93 lines of code

  total lines: 413

  That's all Folks!

