[package]
name = "executive"
version = "0.1.0"
edition = "2021"

[dependencies]
input           = { path = "../Input" }
compute         = { path = "../Compute" }
console_output  = { path = "../ConsoleOutput" }
file_output     = { path = "../FileOutput" }
