[package]
name = "compute"
version = "0.1.0"
edition = "2021"

[dependencies]
# console_output = { path = "../ConsoleOutput" }
file_utils = { path = "../Fileutils" }
input = { path = "../Input" }

[dev-dependencies]
tempfile = "3"
