[package]
name = "input"
version = "0.1.0"
edition = "2021"

[dependencies]
file_utils = { path = "../Fileutils" }   # however you pull it in

[dev-dependencies]
tempfile = "3"      # tempfile crate from crates.io